version: "3"
services:
  app:
    container_name: smoothieapi-app
    build: .
    environment:
      DATABASE_URL: postgres://docker:docker@smoothieapi-postgresql:5432/mysmoothie
    ports:
      - 8085:4000
    command: npm start

  db:
    container_name: smoothieapi-postgresql
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=mysmoothie
    volumes:
      - ./server/common/database/data/sql/:/docker-entrypoint-initdb.d
#      - ./data/postgres:/var/lib/postgresql/data
