const JUS = [
  { id: 1, name: 'Jus d\'orange', gout: 1 },
  { id: 2, name: 'Jus de citron', gout: 1 },
  { id: 3, name: 'Jus d\'ananas', gout: 1 },
  { id: 4, name: 'Jus de pomme', gout: 4 },
];
const GOUTS = [
  { id: 1, name: 'acide' },
  { id: 2, name: 'amer' },
  { id: 3, name: 'sale' },
  { id: 4, name: 'sucre' },
];
const SMOOTHIES = [
  { id: 1, name: 'Banane Mangue et jus d\'Ananas', jus: 3, description: 'Ce smoothie à la fois sucré et acide est parfait pour les amoureux de la mangue et des bananes' },
];
const TYPES = [
  { id: 1, name: 'fruit' },
  { id: 2, name: 'legume' },
];
const FRUITS = [
  { id: 1, name: 'Abricot', type: 1, preparation: 'Dénoyautez et coupez l\'abricot en morceaux' },
  { id: 2, name: 'Ananas', type: 1, preparation: 'Epeluchez et coupez l\'ananas en morceaux' },
  { id: 3, name: 'Avocat', type: 1, preparation: 'Epeluchez, dénoyautez et coupez les avocats en morceaux' },
  { id: 4, name: 'Banane', type: 1, preparation: 'Epelez et coupez le banane en morceaux' },
  { id: 5, name: 'Betterave', type: 2, preparation: 'Epeluchez et coupez les bétteraves rouges en morceaux' },
  { id: 6, name: 'Carotte', type: 2, preparation: 'Epeluchez et coupez la carotte en morceaux' },
  { id: 7, name: 'Citron jaune', type: 1, preparation: 'Epeluchez et coupez le citron en morceaux' },
  { id: 8, name: 'Citron vert', type: 1, preparation: 'Epeluchez et coupez le citron en morceaux' },
  { id: 9, name: 'Concombre', type: 2, preparation: 'Epeluchez et coupez le concombre en morceaux' },
  { id: 10, name: 'Coriandre', type: 2, preparation: 'Ajoutez 3 à 4 feuilles' },
  { id: 11, name: 'Figue', type: 1, preparation: 'coupez la figue en morceaux' },
  { id: 12, name: 'Fruit de la passion', type: 1, preparation: 'Coupez le fruit en deux puis récupérez sa pulpe à l\'aide d\'une cuillère' },
  { id: 13, name: 'Canneberge', type: 1, preparation: '(optionnel) Coupez les canneberges en deux pour en enlever les pépins' },
  { id: 14, name: 'Cassis', type: 1, preparation: '(optionnel) Coupez les cassis en deux pour en enlever les pépins' },
  { id: 15, name: 'Cerise', type: 1, preparation: '(optionnel) Coupez les cassis en deux pour en enlever les pépins' },
  { id: 16, name: 'Fraise', type: 1, preparation: '(optionnel) Coupez la partie haute de la fraise' },
  { id: 17, name: 'Framboise', type: 1, preparation: '(optionnel) Coupez la partie haute de la framboise' },
  { id: 18, name: 'Groseille', type: 1, preparation: '(optionnel) Coupez les groseilles en deux pour en enlever les pépins' },
  { id: 19, name: 'Mûre', type: 1, preparation: '(optionnel) Mixez les mures et passez les au chinois pour retirer les pépins' },
  { id: 20, name: 'myrtille', type: 1, preparation: '(optionnel) Mixez les myrtilles et passez les au chinois pour retirer les pépins' },
  { id: 21, name: 'Gingembre', type: 'tubercule', preparation: 'Epelez le gingembre et coupez le gingembre en morceau' },
  { id: 22, name: 'Grenade', type: 1, preparation: 'Épluchez, coupez et mixez les grenades en utilisant un tamis (pour enlever les grains de grenade)' },
  { id: 23, name: 'Kaki', type: 1, preparation: 'Pelez et coupez les kakis en morceaux' },
  { id: 24, name: 'Kiwi', type: 1, preparation: 'Pelez et coupez les kiwis en morceaux' },
  { id: 25, name: 'Litchi', type: 1, preparation: 'Pelez et dénoyautez les litchis' },
  { id: 26, name: 'Mangue', type: 1, preparation: 'Pelez et coupez la mangue en morceaux' },
  { id: 27, name: 'Melon', type: 1, preparation: 'Pelez et coupez le melon en morceaux' },
  { id: 28, name: 'Menthe', type: 1, preparation: 'Ajoutez 3 à 4 feuilles de menthes' },
  { id: 29, name: 'Mirabelle', type: 1, preparation: 'Epeluchez et coupez la pomme en morceaux' },
  { id: 30, name: 'Noix de coco', type: 1, preparation: 'Ajoutez 15cl de lait de coco' },
  { id: 31, name: 'Orange', type: 1, preparation: 'Pelez et coupez l\'orange en morceaux' },
  { id: 32, name: 'Orange sanguine', type: 1, preparation: 'Pelez et coupez l\'orange en morceaux' },
  { id: 33, name: 'Pamplemousse', type: 1, preparation: 'Pelez et coupez la pamplemousse en morceaux' },
  { id: 34, name: 'Papaye', type: 1, preparation: 'Pelez, enlever les pépins et coupez la papaye en morceaux' },
  { id: 35, name: 'Pastèque', type: 1, preparation: 'Coupez la pastèque en deux, coupez y des petits morceaux en prenant soin d\'enlever les pépins' },
  { id: 36, name: 'Nectarine', type: 1, preparation: 'Pelez et coupez la nectarine en morceaux' },
  { id: 37, name: 'Pêche blanche', type: 1, preparation: 'Pelez et coupez la pêche en morceaux' },
  { id: 38, name: 'Pêche jaune', type: 1, preparation: 'Pelez et coupez la pêche en morceaux' },
  { id: 39, name: 'Poire', type: 1, preparation: 'Pelez et coupez la poire en morceaux' },
  { id: 40, name: 'Pomme', type: 1, preparation: 'Pelez et coupez la pomme en morceaux' },
  { id: 41, name: 'Raisin', type: 1, preparation: '(optionnel) Coupez les raisins en deux pour en enlever les pépins' },
  { id: 42, name: 'Rhubarbe', type: 2, preparation: 'Pelez et coupez la rhubarbe en morceaux' },
  { id: 43, name: 'Rose', type: 1, preparation: 'Ajoutez 3 à 4 feuilles de rose' },
  { id: 44, name: 'Tomate', type: 1, preparation: 'Pelez et coupez la tomate en morceaux' },
];

const SMOOTHIE_FRUIT = [
  { id: 1, smoothie: 1, fruit: 2 },
  { id: 2, smoothie: 1, fruit: 27 },
];
const FRUIT_GOUT = [
  { id: 1, fruit: 1, gout: 4 },
  { id: 2, fruit: 2, gout: 4 },
  { id: 3, fruit: 2, gout: 1 },
  { id: 4, fruit: 3, gout: 3 },
  { id: 5, fruit: 3, gout: 2 },
  { id: 6, fruit: 4, gout: 4 },
  { id: 7, fruit: 5, gout: 3 },
  { id: 8, fruit: 6, gout: 3 },
  { id: 9, fruit: 7, gout: 4 },
  { id: 10, fruit: 7, gout: 1 },
  { id: 11, fruit: 8, gout: 4 },
  { id: 12, fruit: 8, gout: 1 },
  { id: 13, fruit: 9, gout: 2 },
  { id: 14, fruit: 10, gout: 3 },
  { id: 15, fruit: 11, gout: 4 },
  { id: 16, fruit: 12, gout: 4 },
  { id: 17, fruit: 13, gout: 4 },
  { id: 18, fruit: 14, gout: 4 },
  { id: 19, fruit: 15, gout: 4 },
  { id: 20, fruit: 16, gout: 4 },
  { id: 21, fruit: 17, gout: 4 },
  { id: 22, fruit: 18, gout: 4 },
  { id: 23, fruit: 19, gout: 4 },
  { id: 24, fruit: 20, gout: 4 },
  { id: 25, fruit: 21, gout: 4 },
  { id: 26, fruit: 21, gout: 1 },
  { id: 27, fruit: 22, gout: 4 },
  { id: 28, fruit: 22, gout: 4 },
  { id: 29, fruit: 23, gout: 4 },
  { id: 30, fruit: 24, gout: 4 },
  { id: 31, fruit: 24, gout: 1 },
  { id: 32, fruit: 25, gout: 4 },
  { id: 33, fruit: 26, gout: 4 },
  { id: 34, fruit: 27, gout: 4 },
  { id: 35, fruit: 28, gout: 4 },
  { id: 36, fruit: 29, gout: 4 },
  { id: 37, fruit: 30, gout: 4 },
  { id: 38, fruit: 31, gout: 4 },
  { id: 39, fruit: 31, gout: 1 },
  { id: 41, fruit: 32, gout: 4 },
  { id: 42, fruit: 32, gout: 1 },
  { id: 43, fruit: 33, gout: 4 },
  { id: 44, fruit: 33, gout: 1 },
  { id: 45, fruit: 34, gout: 4 },
  { id: 46, fruit: 35, gout: 4 },
  { id: 47, fruit: 36, gout: 4 },
  { id: 48, fruit: 37, gout: 4 },
  { id: 59, fruit: 38, gout: 4 },
  { id: 50, fruit: 39, gout: 4 },
  { id: 51, fruit: 40, gout: 4 },
  { id: 52, fruit: 41, gout: 4 },
  { id: 53, fruit: 42, gout: 4 },
  { id: 54, fruit: 43, gout: 4 },
  { id: 55, fruit: 44, gout: 4 },
  { id: 56, fruit: 44, gout: 1 },
  { id: 57, fruit: 44, gout: 2 },
];

export { JUS, GOUTS, FRUITS, SMOOTHIES, TYPES, SMOOTHIE_FRUIT, FRUIT_GOUT };
