swagger: "2.0"
info:
  version: 1.0.0
  title: MySmoothieApi
  description: My cool smoothie api
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  Fruit:
    type: object
    title: fruit
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress
      type:
        type: string
        example: no_stress
      preparation:
        type: string
        example: no_stress

  Smoothie:
    type: object
    title: smoothie
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress
      jus:
        type: object
        example: no_stress
      fruits:
        type: array
        items:
          $ref: "#/definitions/Fruit"
      description:
        type: string
        example: no_stress

paths:
  /smoothies:
    get:
      tags:
        - Smoothies
      description: Fetch all smoothies
      responses:
        200:
          description: Returns all smoothies
    post:
      tags:
        - Smoothies
      description: Create a new smoothie
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: smoothie
          in: body
          description: an smoothie
          required: true
          schema:
            $ref: "#/definitions/Smoothie"
      responses:
        200:
          description: Return smoothie

  /smoothies/{id}:
    get:
      tags:
        - Smoothies
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the smoothie to retrieve
          type: integer
      responses:
        200:
          description: Return the smoothie with the specified id
        404:
          description: Smoothies not found

  /fruits:
    get:
      tags:
        - Fruits
      description: Fetch all fruits
      responses:
        200:
          description: Returns all fruits

  /fruits/{id}:
    get:
      tags:
        - Fruits
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the fruits to retrieve
          type: integer
      responses:
        200:
          description: Return the fruits with the specified id
        404:
          description: Fruits not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification