swagger: "2.0"
info:
  version: 1.0.0
  title: MySmoothieApi
  description: My cool smoothie api
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

paths:
  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /smoothies:
    get:
      tags:
        - Smoothies
      description: Fetch all smoothies
      responses:
        200:
          description: Returns all smoothies
    post:
      tags:
        - Smoothies
      description: Create a new smoothie
      parameters:
        - name: smoothie
          in: body
          description: an smoothie
          required: true
          schema:
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all smoothies

  /smoothies/{id}:
    get:
      tags:
        - Smoothies
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the smoothie to retrieve
          type: integer
      responses:
        200:
          description: Return the smoothie with the specified id
        404:
          description: Smoothies not found

  /fruits:
    get:
      tags:
        - Fruits
      description: Fetch all fruits
      responses:
        200:
          description: Returns all fruits
    post:
      tags:
        - Fruits
      description: Create a new fruit
      parameters:
        - name: fruit
          in: body
          description: an fruit
          required: true
          schema:
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all fruits

  /fruits/{id}:
    get:
      tags:
        - Fruits
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the fruits to retrieve
          type: integer
      responses:
        200:
          description: Return the fruits with the specified id
        404:
          description: Fruits not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification